[project]
name = "CondaRTS"
version = "0.0.1"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pygame-ce>=2.5.5",
]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "ruff>=0.13.0",
]

[tool.ruff.lint]
select = ["I"]

[tool.ruff.lint.per-file-ignores]
"CondaRTS.py" = [
    "COM812",  # Trailing comma missing - conflicts with ruff format
]
